In [2]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 341.5 kB/s eta 0:00:00a 0:00:01


In [3]:
import numpy as np

#  create array using numpy
arr1= np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
5


In [5]:
arr2= np.array([1,2,3,4,5])
arr2.resize(1,5)
print(arr2)

[[1 2 3 4 5]]


In [6]:
arr2= np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
import numpy as np
arr= np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3)

: 